---
- hosts: all
  gather_facts: yes
  roles:
    - common
    - munge
    - slurm_common
    - node_exporter
    - sssd

- hosts: rocky-slurmctld
  roles:
    - slurm_controller

- hosts: rocky-slurmctld2
  roles:
    - slurm_backup_controller

- hosts: compute
  roles:
    - slurm_compute

- hosts: monitor
  roles:
    - monitoring_server
