all:
  vars:
    ansible_user: olusegun_inetianbor_amii_ca
    ansible_become: true

  children:
    mgmt:
      hosts:
        rocky-slurmctld:
          ansible_host: 10.2.0.3
        rocky-slurmctld2:
          ansible_host: 10.2.0.7

    monitor:
      hosts:
        rocky-monitor:
          ansible_host: 10.2.0.5

    compute:
      hosts:
        rocky-compute:
          ansible_host: 10.2.0.4
        rocky-compute2:
          ansible_host: 10.2.0.6
